### ISSUE TITLE
Double ECS cluster?

### ISSUE THREAD

**Issue by stevie-** [cn-terraform/terraform-aws-nexus#3]
It seems to me, that there are two ecs cluster created.

first from this code here:
https://github.com/cn-terraform/terraform-aws-nexus/blob/0.0.3-alpha/main.tf#L1-L7

```hcl
# ---------------------------------------------------------------------------------------------------------------------
# ECS Cluster
# ---------------------------------------------------------------------------------------------------------------------
resource "aws_ecs_cluster" "nexus_cluster" {
  name = "${var.name_preffix}-nexus"
}

```
and second from here used fargate module:
https://github.com/cn-terraform/terraform-aws-ecs-fargate/blob/master/main.tf#L1-L10
which is referenced here
https://github.com/cn-terraform/terraform-aws-nexus/blob/0.0.3-alpha/main.tf#L21

**Comment by jnonino** [comment]
Fixed in version [1.0.0](https://registry.terraform.io/modules/cn-terraform/nexus/aws/1.0.0)
