### ISSUE TITLE
Error when creating task td

### ISSUE THREAD

**Issue by idjemaoune** [cn-terraform/terraform-aws-nexus#35]
CannotStartContainerError: Error response from daemon: failed to initialize logging driver: failed to create Cloudwatch log stream: ResourceNotFoundException: The specified log group does not exist

**Comment by jnonino** [comment]
Hi @idjemaoune, I merged your PR. Please check if new version if working as expected.
https://github.com/cn-terraform/terraform-aws-nexus/releases/tag/1.0.27

**Comment by idjemaoune** [comment]
Hi @jnonino, yes it work as expected. Thanks ;)
