### ISSUE TITLE
Mount volume to fargate

### ISSUE THREAD

**Issue by jnonino** [cn-terraform/terraform-aws-nexus#4]

**Comment by lefterisALEX** [comment]
Hello,

I tried the latest version and getting the following issue:
`  on .terraform/modules/nexus.ecs_fargate.td.container_definition/main.tf line 17, in locals:
  17:   mount_points = length(var.mount_points) > 0 ? [
    |----------------
    | var.mount_points is null
`
i guess this ticket is about that issue. Is there a way to workaround it?

**Comment by michaelm-88** [comment]
also i just wanted to ask how are you specifying the nexus version ?

**Comment by jnonino** [comment]
Hi,

@lefterisALEX this ticket is not about that error. This ticket is about using EFS to store Nexus files. Please check version 1.0.10 . I think your issue should be fixed there.

@michaelm-88 In version 1.0.10 you can set the nexus image you want to use.
