### ISSUE TITLE
How to get nexus admin PW

### ISSUE THREAD

**Issue by stevie-** [cn-terraform/terraform-aws-nexus#5]
When we run nexus in fargate an initial admin pw is stored inside the container at `/nexus-data/admin.password`

But on fargate we can NOT run something like
```
docker container exec -it $(docker ps -q --filter "name=nexus") cat /nexus-data/admin.password 
```

How do you set/get the admin password?

**Comment by jnonino** [comment]
Hi, I have submitted a new version ([1.0.1](https://registry.terraform.io/modules/cn-terraform/nexus/aws/1.0.1)). There you should be able to see the current password on the logs.

```
**********
**********
**********
admin user current password:  e086d4ef-df9d-4a12-8826-ca9e6e2f31cc
**********
**********
**********
```

**Comment by stevie-** [comment]
Maybe you can also look into environment variable `NEXUS_SECURITY_RANDOMPASSWORD`.
When this is set to `false` the old default PW is used.

Showing the password in logs is a security issue.

**Comment by jnonino** [comment]
Do you prefer to have the old password?

I thought the is no issue on showing it on the logs because when you first login using that password with admin user it asked you to change the password. Which option is better for you?

**Comment by stevie-** [comment]
The good point of the ENV var is, that you don't need to have your own docker image with a modification. Thus I would prefer this.

**Comment by jnonino** [comment]
Please try with the new version [1.0.3](https://registry.terraform.io/modules/cn-terraform/nexus/aws/1.0.3). I did not have time to test it on AWS yet but I tested with the Docker image and setting the variable worked setting the old password.
Please close the issue if it works
